version: '3.7'

services:
  apache:
    build: ./app
    restart: always
    container_name: my-apache
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./app/public_html:/usr/local/apache2/htdocs/