FROM httpd:2.4


COPY ./configs/my-httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./certs/server1.crt /usr/local/apache2/conf/server.crt
COPY ./certs/server1.key /usr/local/apache2/conf/server.key
